// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-VPSOccYc-TksvI3w4haEMSNDCyRP3F4',
    appId: '1:42856190078:web:2aaf0b65a7719198bbc82f',
    messagingSenderId: '42856190078',
    projectId: 'fitora-03',
    authDomain: 'fitora-03.firebaseapp.com',
    storageBucket: 'fitora-03.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnhEWutAnjGr18cHHcpHHNo41DkYKa8CA',
    appId: '1:42856190078:android:945ea43bff22e8eebbc82f',
    messagingSenderId: '42856190078',
    projectId: 'fitora-03',
    storageBucket: 'fitora-03.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD726x9YajJbYkt4MnRstQ4biopWpSEBtc',
    appId: '1:42856190078:ios:e41d5a974c9b0ec0bbc82f',
    messagingSenderId: '42856190078',
    projectId: 'fitora-03',
    storageBucket: 'fitora-03.firebasestorage.app',
    iosClientId: '42856190078-bbd1j3hqgcr8jv8ge2ekagd4j84sosbj.apps.googleusercontent.com',
    iosBundleId: 'com.example.fitora',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD726x9YajJbYkt4MnRstQ4biopWpSEBtc',
    appId: '1:42856190078:ios:e41d5a974c9b0ec0bbc82f',
    messagingSenderId: '42856190078',
    projectId: 'fitora-03',
    storageBucket: 'fitora-03.firebasestorage.app',
    iosClientId: '42856190078-bbd1j3hqgcr8jv8ge2ekagd4j84sosbj.apps.googleusercontent.com',
    iosBundleId: 'com.example.fitora',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD-VPSOccYc-TksvI3w4haEMSNDCyRP3F4',
    appId: '1:42856190078:web:963aa886dc304321bbc82f',
    messagingSenderId: '42856190078',
    projectId: 'fitora-03',
    authDomain: 'fitora-03.firebaseapp.com',
    storageBucket: 'fitora-03.firebasestorage.app',
  );
}
